### PR TITLE
exit with code 1 when build fails

### LINKED ISSUE #54: exit code is 0 when build failed
When the build fails the exit code of backpack is 0. 

That makes it necessary to capture backpacks output and parse it to use it in a CI.

### PR DESCRIPTION
**Pull request by despairblue**
fixes #54

### CODE REVIEW

**Comment by despairblue** [comment]
This is probably a breaking change, if people relied on the fact that backback exited with code 0 on failure.

**Comment by jaredpalmer** [comment]
This is from another project we use internally... will this work?

```js
....

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', err => {
  throw err;
});

compile(serverConfig, (err, serverStats) => {
  handleWebpackErrors(err, serverStats)
  console.log(chalk.green('Compiled successfully'))
})

// Wrap webpack compile in a try catch.
function compile(config, cb) {
  let compiler;
  try {
    compiler = webpack(config);
  } catch (e) {
    printErrors('Failed to compile.', [e]);
    process.exit(1);
  }
  compiler.run((err, stats) => {
    cb(err, stats);
  });
}

// Print out errors
function printErrors(summary, errors) {
  console.log(chalk.red(summary));
  console.log();
  errors.forEach(err => {
    console.log(err.message || err);
    console.log();
  });
}

// Gracefully handle errors and print them to console.
function handleWebpackErrors(err, stats) {
  if (err) {
    printErrors('Failed to compile.', [err]);
    process.exit(1);
  }

  if (stats.compilation.errors && stats.compilation.errors.length) {
    printErrors('Failed to compile.', stats.compilation.errors);
    process.exit(1);
  }
  if (
    process.env.CI &&
    stats.compilation.warnings &&
    stats.compilation.warnings.length
  ) {
    printErrors(
      'Failed to compile. When process.env.CI = true, warnings are treated as failures. Most CI servers set this automatically.',
      stats.compilation.warnings
    );
    process.exit(1);
  }
}

```

**Comment by despairblue** [comment]
@jaredpalmer Yeah that works as well, but it will duplicate the output in the error case:
screen shot 2017-03-29 at 19 06 24

**Comment by jaredpalmer** [comment]
@despairblue yeah, i pulled it from a project that has a custom webpack logging plugin. Forgot that backpack has that totally baked in tbh.

**Comment by despairblue** [comment]
@jaredpalmer So how are we going to proceed from here? 😄 
Should I change anything?

**Comment by despairblue** [comment]
@jaredpalmer hey, is anything holding back a new release? Can I help somehow?

**Comment by jaredpalmer** [comment]
@despairblue done.

**Comment by despairblue** [comment]
You are awesome, I was just running `yarn upgrade-interactive` again and wondering if I just missed it in the output the first time 😄 

👏

**Pull request merged**
